name: pbl
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - attrs=24.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.15.1
  - colorama=0.4.6
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dlib=19.22.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - fonttools=4.38.0
  - freetype=2.12.1
  - icu=58.2
  - idna=3.10
  - importlib-metadata=4.11.4
  - importlib_resources=6.0.0
  - intel-openmp=2024.2.1
  - ipykernel=6.16.2
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=4.11.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.3.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libtiff=4.2.0
  - libwebp=1.0.2
  - libxml2=2.12.7
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2024.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=1.1.0
  - nbclient=0.7.0
  - nbconvert-core=7.6.0
  - nbformat=5.8.0
  - nest-asyncio=1.6.0
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numpy=1.21.6
  - olefile=0.47
  - opencv=4.0.1
  - openjpeg=2.4.0
  - openssl=1.0.2u
  - packaging=23.2
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.48
  - psutil=5.9.3
  - pthreads-win32=2.9.1
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.4
  - pyqt=5.6.0
  - pyrsistent=0.18.1
  - python=3.7.1
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python_abi=3.7
  - pytz=2024.2
  - pywin32=303
  - pywinpty=2.0.8
  - pyzmq=24.0.1
  - qt=5.6.2
  - ruptures=1.1.7
  - scipy=1.7.3
  - send2trash=1.8.3
  - setuptools=59.8.0
  - sip=4.18.1
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.3.2.post1
  - sqlite=3.46.1
  - tbb=2021.13.0
  - terminado=0.17.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - ucrt=10.0.22621.0
  - unicodedata2=14.0.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.10
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.42.0
  - winpty=0.4.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.6
